# Generated by Django 6.1 on 2026-08-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('INMOBILIARIO', 'Inmobiliario (mesas, sillas, mantelería, vajilla)'), ('BANQUETE', 'Banquete (alimentos, bebidas, degustación)'), ('MUSICA', 'Música / DJ'), ('ILUMINACION', 'Iluminación'), ('DECORACION', 'Decoración'), ('COORDINACION', 'Coordinación del evento')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=120)),
                ('cliente_email', models.EmailField(max_length=254)),
                ('fecha_evento', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('productos', models.ManyToManyField(related_name='pedidos', to='solicitudes.producto')),
            ],
        ),
    ]
